# -*- coding: utf-8 -*-
"""Data Analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dSfG64iw0Yjryooa3XjVfqhajAZMTQUd
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(10)

months = np.arange(1,25)

df = pd.DataFrame({
    "Month": months,
    "Region": np.random.choice(["North","South","East","West"],24),
    "Units_Sold": np.random.randint(10,100,24),
    "Price_per_Unit": np.random.uniform(50,500,24).round(2)
})

df["Total_Revenue"] = df["Units_Sold"] * df["Price_per_Unit"]

# Statistics
print(df.describe())

# Bar Chart
df.groupby("Region")["Total_Revenue"].sum().plot(kind="bar")
plt.title("Revenue by Region")
plt.show()

# Line Chart
df.groupby("Month")["Total_Revenue"].sum().plot(kind="line")
plt.title("Monthly Revenue Trend")
plt.show()